# Generated by Django 5.1.2 on 2024-10-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="caughtmessage",
            name="channel",
            field=models.CharField(default="sadad", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="caughtmessage",
            name="ts",
            field=models.DecimalField(decimal_places=6, default=123.12, max_digits=20),
            preserve_default=False,
        ),
    ]
